# Explore the Zhuang-ABCA Dataset

Dataset: https://alleninstitute.github.io/abc_atlas_access/descriptions/Zhuang-ABCA-1.html

Manuscript: https://www.nature.com/articles/s41586-023-06808-9

In [1]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path.cwd().parent.parent / "src"))

In [2]:
import scanpy as sc

adata_abca_1 = sc.read_h5ad('data/zhuang-abca-1/Zhuang-ABCA-1-raw.h5ad')
adata_abca_1

AnnData object with n_obs × n_vars = 4167870 × 1122
    obs: 'brain_section_label'
    var: 'gene_symbol'

In [3]:
import pandas as pd

cells_abca_1 = pd.read_csv('data/zhuang-abca-1/cell_metadata.csv')
cells_abca_1

,cell_label,brain_section_label,feature_matrix_label,donor_label,donor_genotype,donor_sex,cluster_alias,x,y,z,subclass_confidence_score,cluster_confidence_score,high_quality_transfer,abc_sample_id
0,182941331246012878296807398333956011710,Zhuang-ABCA-1.089,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,704,0.682522,3.366483,7.829530,0.969933,0.718088,True,79bda012-4dd4-43d7-8f66-1f29997f6780
1,221260934538535633595532020856387724686,Zhuang-ABCA-1.089,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,5243,0.667690,3.442241,7.829530,0.850554,0.850554,True,2f0b3159-2766-4f9e-a8cd-8dd16bae05fa
2,22228792606814781533240955623030943708,Zhuang-ABCA-1.089,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,14939,0.638731,3.474328,7.829530,0.888285,0.649581,True,fe1f5f73-5afb-4e51-b4f0-cf6690257086
3,272043042552227961220474294517855477150,Zhuang-ABCA-1.089,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,14939,0.653425,3.433218,7.829530,0.900000,0.607080,True,a13e1c1c-9828-4d3b-9aae-e2ab055a39ad
4,110116287883089187971185374239350249328,Zhuang-ABCA-1.089,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,5254,0.623896,3.513574,7.829530,0.999978,0.689511,True,add02bc8-456b-486c-9f13-db578c62cc5a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2846903,94310525370042131911495836073267655162,Zhuang-ABCA-1.110,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,5255,0.997247,3.823236,9.717769,0.971385,0.943456,True,3e178fe9-3440-4cf1-ab79-2192d25e3d02
2846904,298798481479578578007190103666214714353,Zhuang-ABCA-1.110,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,14939,1.043871,3.706231,9.717769,0.956377,0.905493,True,22cfcaf3-0c26-41b7-ab14-f76398fd18a4
2846905,330756942354980576352210203729462562749,Zhuang-ABCA-1.110,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,5261,1.037680,3.759890,9.717769,0.811520,0.788901,True,bc4eb252-c3fd-4ba0-9739-70eff08b29fe
2846906,47305871059582831548494138048361484565,Zhuang-ABCA-1.110,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,5252,1.044169,3.758463,9.717769,0.991924,0.634152,True,f450f6fa-667b-40bf-a865-000131b57d2c
2846907,64578198410898899234789748167671783948,Zhuang-ABCA-1.110,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,5263,1.042301,3.589421,9.717769,0.889413,0.645770,True,11b45e69-80fe-4cd7-9480-ce3a04a9b1c5

In [4]:
import pandas as pd

ccf_1 = pd.read_csv('data/zhuang-abca-1/ccf_coordinates.csv')
ccf_1

,cell_label,x,y,z,parcellation_index
0,182941331246012878296807398333956011710,7.902190,3.048426,0.582962,0
1,221260934538535633595532020856387724686,7.906513,3.145200,0.577602,0
2,22228792606814781533240955623030943708,7.906110,3.182761,0.553731,0
3,272043042552227961220474294517855477150,7.904627,3.131808,0.563525,0
4,110116287883089187971185374239350249328,7.907236,3.230647,0.543048,0
...,...,...,...,...,...
2616323,94310525370042131911495836073267655162,9.681244,4.453979,0.852027,0
2616324,298798481479578578007190103666214714353,9.676999,4.291647,0.899531,1109
2616325,330756942354980576352210203729462562749,9.678760,4.363282,0.894082,1109
2616326,47305871059582831548494138048361484565,9.678641,4.360346,0.901195,1109
2616327,64578198410898899234789748167671783948,9.673530,4.138034,0.897311,1109

In [5]:
# how many slices does zhuang-abca-1 contain? How many cells per sample?
# `abc_sample_id`: an individual sample (animal / batch / experiment)
# `brain_section_label`: a brain slice of one sample

print('How many slices does `zhuang-abca-1` contain? How many cells per slice?\n')
print(
    cells_abca_1["brain_section_label"].value_counts().describe(percentiles=[.01, .05, .1, .25, .5, .75, .9, .95, .99]))

How many slices does `zhuang-abca-1` contain? How many cells per slice?

count      147.000000
mean     19366.721088
std       7873.557243
min       5505.000000
1%        6499.280000
5%        8146.400000
10%       9433.000000
25%      11351.000000
50%      19809.000000
75%      26247.000000
90%      29212.200000
95%      30827.100000
99%      33768.080000
max      37068.000000
Name: count, dtype: float64

In [6]:
# how many brain sections does zhuang-abca-1 contain?


print('How many brain sections does `zhuang-abca-1` contain? How many cells per brain section?\n')
print(ccf_1["parcellation_index"].value_counts().describe(percentiles=[.01, .05, .1, .25, .5, .75, .9, .95, .99]))

How many brain sections does `zhuang-abca-1` contain? How many cells per brain section?

count       680.000000
mean       3847.541176
std        8349.762317
min           7.000000
1%           35.000000
5%           97.900000
10%         174.600000
25%         505.000000
50%        1434.500000
75%        4099.000000
90%        9049.300000
95%       14115.000000
99%       33650.580000
max      148457.000000
Name: count, dtype: float64

In [7]:
# given a brain section, how many samples include the section and how many cells are in this section per sample?
import pandas as pd

ccf_cell_1 = pd.merge(cells_abca_1, ccf_1, how='left', on='cell_label')
ccf_cell_1.groupby('parcellation_index')

print('Given a brain section, how many slices include the section?\n')
print(ccf_cell_1.groupby('parcellation_index')['brain_section_label'].nunique().describe(
    percentiles=[.01, .05, .1, .25, .5, .75, .9, .95, .99]))

Given a brain section, how many slices include the section?

count    680.000000
mean      16.200000
std       12.325411
min        1.000000
1%         1.790000
5%         3.000000
10%        5.000000
25%        8.000000
50%       13.000000
75%       22.000000
90%       31.000000
95%       38.000000
99%       53.420000
max      129.000000
Name: brain_section_label, dtype: float64

In [8]:
from NicheQueryPrototype.database import Database

parcellation_tree = Database().parse_parcellation_structure(json_path='data/parcellation/structure.json')
ccf_cell_1['parcellation_level'] = ccf_cell_1['parcellation_index'].map(
    lambda k: parcellation_tree.get(k, {}).get("st_level", -1))

s = (ccf_cell_1
     .groupby(["parcellation_level", "parcellation_index"])["brain_section_label"]
     .nunique())

print('Given a brain section, how many slices include the section group by brain section level?\n')
print(s.groupby(level=0).describe(percentiles=[.01, .05, .1, .25, .5, .75, .9, .95, .99]))

Given a brain section, how many slices include the section group by brain section level?

                    count       mean        std   min     1%     5%   10%  \
parcellation_level
-1                   87.0  12.333333  15.620996   1.0   1.86   3.00   4.0
 0                    1.0  25.000000        NaN  25.0  25.00  25.00  25.0
 1                    4.0  20.250000  12.996794   9.0   9.06   9.30   9.6
 2                    4.0  22.500000   5.802298  14.0  14.30  15.50  17.0
 3                    2.0  44.000000  60.811183   1.0   1.86   5.30   9.6
 5                    6.0   9.500000   5.167204   3.0   3.15   3.75   4.5
 6                   21.0  20.142857  18.399146   2.0   2.40   4.00   5.0
 7                   18.0  18.388889  12.659053   3.0   3.17   3.85   4.7
 8                  183.0  16.786885  11.742355   1.0   1.82   4.00   5.0
 9                  128.0  16.273438   9.965069   1.0   2.00   3.35   4.7
 10                  34.0  16.794118  14.216464   2.0   2.00   2.65   3.3
 11                 192.0  16.260417  10.219830   1.0   1.91   4.00   5.0

                      25%   50%    75%   90%    95%    99%    max
parcellation_level
-1                   6.00   9.0  12.00  22.4  29.40  73.10  129.0
 0                  25.00  25.0  25.00  25.0  25.00  25.00   25.0
 1                  10.50  17.5  27.25  33.1  35.05  36.61   37.0
 2                  21.50  24.5  25.50  26.4  26.70  26.94   27.0
 3                  22.50  44.0  65.50  78.4  82.70  86.14   87.0
 5                   6.50   9.5  11.00  14.5  16.25  17.65   18.0
 6                   9.00  15.0  26.00  34.0  46.00  77.20   85.0
 7                   7.50  16.5  23.25  37.9  40.30  41.66   42.0
 8                   8.00  13.0  23.00  33.6  40.00  53.36   59.0
 9                   8.75  14.5  24.25  27.3  35.65  39.46   47.0
 10                  6.50  12.5  18.75  33.7  45.70  58.39   64.0
 11                  8.75  14.0  22.25  29.9  37.45  46.18   48.0

In [9]:
s = (ccf_cell_1
     .groupby(["parcellation_level"])["parcellation_index"]
     .nunique())

print('# parcellations group by levels\n')
print(s)

# parcellations group by levels

parcellation_level
-1      87
 0       1
 1       4
 2       4
 3       2
 5       6
 6      21
 7      18
 8     183
 9     128
 10     34
 11    192
Name: parcellation_index, dtype: int64

In [10]:
s = (ccf_cell_1
     .groupby(["parcellation_level", "parcellation_index"])["cell_label"]
     .nunique())

print('Given a brain section, how many cells in the brain section per brian slice group by brain section level?\n')
print(s.groupby(level=0).describe(percentiles=[.01, .05, .1, .25, .5, .75, .9, .95, .99]))

Given a brain section, how many cells in the brain section per brian slice group by brain section level?

                    count          mean           std      min        1%  \
parcellation_level
-1                   87.0   2281.172414   6845.261137     11.0     17.02
 0                    1.0  31460.000000           NaN  31460.0  31460.00
 1                    4.0   3533.750000   2216.792785    960.0   1010.37
 2                    4.0   1766.000000    945.802657    881.0    898.04
 3                    2.0   7843.000000  10777.721559    222.0    374.42
 5                    6.0   2186.500000   2574.498844    158.0    175.30
 6                   21.0   5523.666667   7945.489773     47.0     63.40
 7                   18.0   6475.611111   8080.877880     63.0     83.91
 8                  183.0   3248.699454   4790.406886      7.0     16.92
 9                  128.0   4595.515625   8093.391776     55.0     61.43
 10                  34.0   2629.764706   3319.046861     35.0     46.55
 11                 192.0   4331.739583  11768.408610     35.0     39.00

                          5%      10%       25%      50%       75%      90%  \
parcellation_level
-1                     82.10    139.0    262.00    632.0   1249.50   2571.8
 0                  31460.00  31460.0  31460.00  31460.0  31460.00  31460.0
 1                   1211.85   1463.7   2219.25   3550.0   4864.50   5590.8
 2                    966.20   1051.4   1307.00   1541.0   2000.00   2660.6
 3                    984.10   1746.2   4032.50   7843.0  11653.50  13939.8
 5                    244.50    331.0    583.25    881.5   3357.75   5347.0
 6                    129.00    200.0    351.00   1484.0   6409.00  16248.0
 7                    167.55    466.7   1671.50   3139.5   9139.75  16170.8
 8                     83.50    177.2    602.50   1581.0   4413.50   8039.2
 9                    154.85    311.1    610.75   1685.0   4329.50  10393.2
 10                    95.35    135.3    391.50   1194.0   3871.75   5308.2
 11                   113.05    210.8    488.00   1810.5   4251.75   9926.0

                         95%       99%       max
parcellation_level
-1                  10830.40  31154.40   52964.0
 0                  31460.00  31460.00   31460.0
 1                   5832.90   6026.58    6075.0
 2                   2880.80   3056.96    3101.0
 3                  14701.90  15311.58   15464.0
 5                   5939.00   6412.60    6531.0
 6                  18747.00  27930.20   30226.0
 7                  24767.45  27448.69   28119.0
 8                  10305.00  18550.94   45445.0
 9                  20059.60  37458.63   56379.0
 10                  7140.05  14241.18   16470.0
 11                 12527.60  25188.98  148457.0

## Choose a parcellation for spot check

In [11]:
ccf_cell_1

,cell_label,brain_section_label,feature_matrix_label,donor_label,donor_genotype,donor_sex,cluster_alias,x_x,y_x,z_x,subclass_confidence_score,cluster_confidence_score,high_quality_transfer,abc_sample_id,x_y,y_y,z_y,parcellation_index,parcellation_level
0,182941331246012878296807398333956011710,Zhuang-ABCA-1.089,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,704,0.682522,3.366483,7.829530,0.969933,0.718088,True,79bda012-4dd4-43d7-8f66-1f29997f6780,7.902190,3.048426,0.582962,0.0,-1
1,221260934538535633595532020856387724686,Zhuang-ABCA-1.089,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,5243,0.667690,3.442241,7.829530,0.850554,0.850554,True,2f0b3159-2766-4f9e-a8cd-8dd16bae05fa,7.906513,3.145200,0.577602,0.0,-1
2,22228792606814781533240955623030943708,Zhuang-ABCA-1.089,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,14939,0.638731,3.474328,7.829530,0.888285,0.649581,True,fe1f5f73-5afb-4e51-b4f0-cf6690257086,7.906110,3.182761,0.553731,0.0,-1
3,272043042552227961220474294517855477150,Zhuang-ABCA-1.089,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,14939,0.653425,3.433218,7.829530,0.900000,0.607080,True,a13e1c1c-9828-4d3b-9aae-e2ab055a39ad,7.904627,3.131808,0.563525,0.0,-1
4,110116287883089187971185374239350249328,Zhuang-ABCA-1.089,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,5254,0.623896,3.513574,7.829530,0.999978,0.689511,True,add02bc8-456b-486c-9f13-db578c62cc5a,7.907236,3.230647,0.543048,0.0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2846903,94310525370042131911495836073267655162,Zhuang-ABCA-1.110,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,5255,0.997247,3.823236,9.717769,0.971385,0.943456,True,3e178fe9-3440-4cf1-ab79-2192d25e3d02,9.681244,4.453979,0.852027,0.0,-1
2846904,298798481479578578007190103666214714353,Zhuang-ABCA-1.110,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,14939,1.043871,3.706231,9.717769,0.956377,0.905493,True,22cfcaf3-0c26-41b7-ab14-f76398fd18a4,9.676999,4.291647,0.899531,1109.0,8
2846905,330756942354980576352210203729462562749,Zhuang-ABCA-1.110,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,5261,1.037680,3.759890,9.717769,0.811520,0.788901,True,bc4eb252-c3fd-4ba0-9739-70eff08b29fe,9.678760,4.363282,0.894082,1109.0,8
2846906,47305871059582831548494138048361484565,Zhuang-ABCA-1.110,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,5252,1.044169,3.758463,9.717769,0.991924,0.634152,True,f450f6fa-667b-40bf-a865-000131b57d2c,9.678641,4.360346,0.901195,1109.0,8
2846907,64578198410898899234789748167671783948,Zhuang-ABCA-1.110,Zhuang-ABCA-1,Zhuang-ABCA-1,wt/wt,F,5263,1.042301,3.589421,9.717769,0.889413,0.645770,True,11b45e69-80fe-4cd7-9480-ce3a04a9b1c5,9.673530,4.138034,0.897311,1109.0,8

In [12]:
ccf_cell_1.donor_label.nunique()

1

In [13]:
# random select a parcellation & sample

# step 1: print parcellation at a specific level
target_parcellations = ccf_cell_1[ccf_cell_1['parcellation_level'] == 6]['parcellation_index'].unique()
print(f"Check parcellation at level 6: {target_parcellations}")

Check parcellation at level 6: [ 826.  987.  645.  485.  500.  339.  467.  541.  809.  323.  822. 1073.
  818.  864.  141.  669.  856.  157. 1080.  348.  278.]

In [14]:
# random select a parcellation & sample

# step 1: print parcellation at a specific level
target_parcellations = ccf_cell_1[ccf_cell_1['parcellation_level'] == 3]['parcellation_index'].unique()
print(f"Check parcellation at level 2: {target_parcellations}")

Check parcellation at level 2: [688. 623.]

In [16]:
# step 2: check # samples with this parcellation
target_parcellation = 826

with pd.option_context("display.max_rows", None,
                       "display.max_columns", None,
                       "display.width", None,
                       "display.max_colwidth", None):
    s = ccf_cell_1[ccf_cell_1['parcellation_index'] == target_parcellation]['brain_section_label'].value_counts()
    print(
        f"Samples with this parcellation & # cells in this parcellation per sample: \n{s}")
    print(f"Total samples: {s.shape[0]} out of {ccf_cell_1['brain_section_label'].nunique()}")

Samples with this parcellation & # cells in this parcellation per sample:
brain_section_label
Zhuang-ABCA-1.086    52
Zhuang-ABCA-1.104    44
Zhuang-ABCA-1.102    39
Zhuang-ABCA-1.087    39
Zhuang-ABCA-1.090    35
Zhuang-ABCA-1.093    33
Zhuang-ABCA-1.084    31
Zhuang-ABCA-1.088    31
Zhuang-ABCA-1.096    31
Zhuang-ABCA-1.097    30
Zhuang-ABCA-1.099    30
Zhuang-ABCA-1.106    30
Zhuang-ABCA-1.085    29
Zhuang-ABCA-1.089    29
Zhuang-ABCA-1.107    26
Zhuang-ABCA-1.100    25
Zhuang-ABCA-1.103    24
Zhuang-ABCA-1.098    24
Zhuang-ABCA-1.091    24
Zhuang-ABCA-1.083    22
Zhuang-ABCA-1.082    21
Zhuang-ABCA-1.105    20
Zhuang-ABCA-1.092    20
Zhuang-ABCA-1.095    19
Zhuang-ABCA-1.081    18
Zhuang-ABCA-1.101    17
Zhuang-ABCA-1.108     7
Name: count, dtype: int64
Total samples: 27 out of 147